org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

mod.group=at.minecraftschurli.mods
mod.id=arsmagicalegacy
mod.version=1.7.0
mod.name=Ars Magica: Legacy
mod.vendor=MinecraftschurliMods
mod.authors=Minecraftschurli, IchHabeHunger54
mod.description=Continuation of Ars Magica 2 by Mithion
mod.credits=Mithion for the original mod
mod.logo=logo.png
mod.url=https://www.curseforge.com/minecraft/mc-mods/ars-magica-legacy

java_version=25

github.owner=MinecraftschurliMods
github.repo=Ars-Magica-Legacy

license.name=MIT
license.url=https://opensource.org/licenses/MIT

neogradle.subsystems.conventions.runs.create-default-run-per-type=false
neogradle.subsystems.tools.renderDoc.path=renderdoc
neogradle.subsystems.tools.renderDoc.version=1.33
neogradle.subsystems.tools.renderDoc.renderNurse=net.neoforged:render-nurse:0.0.26

mc_version=26.1.2
mc_version_range=[26.1,26.2)

neo_version=26.1.2.95
neo_version_range=[26.1.2.95,26.2)

loader.version=[4,)
junit_version=5.7.1
colorthief_version=1.1.2

dependency.geckolib.version=5.5
dependency.geckolib.version.range=[5.5,6)

dependency.curios.version=15.0.0-beta.1+26.1
dependency.curios.version.range=[15.0.0-beta.1,16)

dependency.jade.version=26.0.6+neoforge
dependency.jade.version.range=[26.0.6,27)

dependency.jei.version=29.5.0.24
dependency.jei.version.range=[29.5,30)

dependency.patchouli.version=26.1-94
dependency.patchouli.version.range=[26.1-94,26.2)

dependency.easydatagenlib.version=26.1-2.1-SNAPSHOT

mc-publish.curseforge=350734
mc-publish.modrinth=hm4S7JIe
