org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

neogradle.subsystems.conventions.runs.create-default-run-per-type=false

mod.group=com.github.minecraftschurlimods
mod.id=arsmagicalegacy
mod.version=1.5.0
mod.name=Ars Magica: Legacy
mod.vendor=MinecraftschurliMods
mod.authors=Minecraftschurli, IchHabeHunger54
mod.description=Continuation of Ars Magica 2 by Mithion
mod.credits=Mithion for the original mod
mod.logo=logo.png
mod.url=https://www.curseforge.com/minecraft/mc-mods/ars-magica-legacy

java_version=21

github.owner=MinecraftschurliMods
github.repo=Ars-Magica-Legacy

license.name="Don't Be a Jerk" License
license.file=LICENSE.md

neogradle.subsystems.parchment.minecraftVersion=1.21
neogradle.subsystems.parchment.mappingsVersion=2024.07.28

mc_version=1.21
mc_version_range=[1.21,1.21.1)

neo_version=21.0.148
neo_version_range=[21.0.143,21.1)

dependency.patchouli.version=1.21-87-NEOFORGE-SNAPSHOT
dependency.patchouli.version.range=[1.21-87,1.21.1)

dependency.geckolib.version=4.5.6
dependency.geckolib.version.range=[4.5,4.6)

dependency.jei.version=19.5.3.67
dependency.jei.version.range=[19,20)

dependency.jade.version=15.1.5+neoforge
dependency.jade.version.range=[15,16)

dependency.curios.version=9.0.5+1.21
dependency.curios.version.range=[9,10)

dependency.embeddium.version=1.0.7+mc1.21
dependency.embeddium.version.range=[1.0.7,)

dependency.theoneprobe.version=1.21_neo-12.0.3-5
dependency.theoneprobe.version.range=*

dependency.potionbundles.version=1.21-1.8-SNAPSHOT
dependency.potionbundles.version.range=*

dependency.catalogue.version=1.21-1.10.1
dependency.catalogue.version.range=*

dependency.configured.version=1.21-2.5.0
dependency.configured.version.range=*

dependency.codeclib.version=[1.21-1.0-SNAPSHOT,)!!1.21-1.0-SNAPSHOT
dependency.betterkeybindlib.version=[1.21-1.1-SNAPSHOT,)!!1.21-1.1-SNAPSHOT
dependency.betterhudlib.version=[1.21-1.0-SNAPSHOT,)!!1.21-1.0-SNAPSHOT
dependency.easydatagenlib.version=1.21-1.1.2-SNAPSHOT

loader.version=[4,)

mc-publish.curseforge=350734
mc-publish.modrinth=hm4S7JIe
