@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.github.minecraftschurlimods.arsmagicalegacy.common.effect;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
