@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.github.minecraftschurli.arsmagicalegacy;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
