package com.github.minecraftschurlimods.arsmagicalegacy.client.model.entity;

import com.github.minecraftschurlimods.arsmagicalegacy.api.ArsMagicaAPI;
import com.github.minecraftschurlimods.arsmagicalegacy.common.entity.ArcaneGuardian;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.Mth;

public class ArcaneGuardianModel extends EntityModel<ArcaneGuardian> {
    public static final ModelLayerLocation LAYER_LOCATION = new ModelLayerLocation(new ResourceLocation(ArsMagicaAPI.MOD_ID, "arcane_guardian"), "main");
    private final ModelPart head;
    private final ModelPart neck;
    private final ModelPart hoodTop;
    private final ModelPart hoodLeft;
    private final ModelPart hoodRight;
    private final ModelPart hoodBack;
    private final ModelPart body;
    private final ModelPart rune;
    private final ModelPart rod;
    private final ModelPart rod1;
    private final ModelPart rod2;
    private final ModelPart rod3;
    private final ModelPart rod4;
    private final ModelPart upperRightArm;
    private final ModelPart lowerRightArm;
    private final ModelPart rightHand;
    private final ModelPart wand;
    private final ModelPart upperLeftArm;
    private final ModelPart lowerLeftArm;
    private final ModelPart leftHand;
    private final ModelPart book;
    private final ModelPart robeTop;
    private final ModelPart robeFront;
    private final ModelPart rightLeg;
    private final ModelPart robeBackRight;
    private final ModelPart robeRight;
    private final ModelPart leftLeg;
    private final ModelPart robeBackLeft;
    private final ModelPart robeLeft;

    public ArcaneGuardianModel(ModelPart root) {
        head = root.getChild("head");
        neck = root.getChild("neck");
        hoodTop = root.getChild("hood_top");
        hoodLeft = root.getChild("hood_left");
        hoodRight = root.getChild("hood_right");
        hoodBack = root.getChild("hood_back");
        body = root.getChild("body");
        rune = root.getChild("rune");
        rod = root.getChild("rod");
        rod1 = root.getChild("rod1");
        rod2 = root.getChild("rod2");
        rod3 = root.getChild("rod3");
        rod4 = root.getChild("rod4");
        upperRightArm = root.getChild("upper_right_arm");
        lowerRightArm = root.getChild("lower_right_arm");
        rightHand = root.getChild("right_hand");
        wand = root.getChild("wand");
        upperLeftArm = root.getChild("upper_left_arm");
        lowerLeftArm = root.getChild("lower_left_arm");
        leftHand = root.getChild("left_hand");
        book = root.getChild("book");
        robeTop = root.getChild("robe_top");
        robeFront = root.getChild("robe_front");
        rightLeg = root.getChild("right_leg");
        robeBackRight = root.getChild("robe_back_right");
        robeRight = root.getChild("robe_right");
        leftLeg = root.getChild("left_leg");
        robeBackLeft = root.getChild("robe_back_left");
        robeLeft = root.getChild("robe_left");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition md = new MeshDefinition();
        PartDefinition pd = md.getRoot();
        ModelUtil.addCube(pd, "head", 100, 44, -3, -7, -3, 7, 7, 7, 0, -4.5f, 0);
        ModelUtil.addCube(pd, "neck", 95, 116, -0.5f, -0.5f, -0.5f, 2, 1, 2, 0, -4, 0);
        ModelUtil.addCube(pd, "hood_top", 94, 34, -4, -8, -3, 9, 1, 8, 0, -4.5f, 0);
        ModelUtil.addCube(pd, "hood_left", 91, 17, -4, -7, -3, 1, 8, 8, 0, -4.5f, 0);
        ModelUtil.addCube(pd, "hood_right", 110, 17, 4, -7, -3, 1, 8, 8, 0, -4.5f, 0);
        ModelUtil.addCube(pd, "hood_back", 112, 7, -3, -7, 4, 7, 8, 1, 0, -4.5f, 0);
        ModelUtil.addCube(pd, "body", 104, 59, -3.5f, -2, -1.5f, 8, 4, 4, 0, -1.5f, 0);
        ModelUtil.addCube(pd, "rune", 0, 0, -21.5f, -22, 10.5f, 44, 44, 0, 0, 2, 0);
        ModelUtil.addCube(pd, "rod", 103, 8, -0.5f, -3, -0.5f, 2, 6, 2, 0, 2.5f, 0);
        ModelUtil.addCube(pd, "rod1", 118, 1, -2, -1.5f, -0.5f, 4, 4, 1, 0.5f, 2.5f, 0.5f, 0, 0, -(float) (Math.PI / 4));
        ModelUtil.addCube(pd, "rod2", 118, 1, -2, -1.5f, -0.5f, 4, 4, 1, 0.5f, 2.5f, 0.5f, (float) (7 * Math.PI / 36), (float) (Math.PI / 6), (float) (11 * Math.PI / 36));
        ModelUtil.addCube(pd, "rod3", 118, 1, -2, -1.5f, -0.5f, 4, 4, 1, 0.5f, 2.5f, 0.5f, (float) (Math.PI / 2), -(float) (Math.PI / 4), -(float) (Math.PI / 2));
        ModelUtil.addCube(pd, "rod4", 118, 1, -2, -1.5f, -0.5f, 4, 4, 1, 0.5f, 2.5f, 0.5f, (float) (7 * Math.PI / 36), -(float) (Math.PI / 6), -(float) (11 * Math.PI / 36));
        ModelUtil.addCube(pd, "upper_right_arm", 103, 68, -7.5f, -2.5f, -1.5f, 4, 5, 4, 0, -1, 0);
        ModelUtil.addCube(pd, "lower_right_arm", 69, 68, -7.5f, 2.5f, -1.5f, 4, 5, 4, 0, -1, 0);
        ModelUtil.addCube(pd, "right_hand", 106, 78, -3, -1, -8.5f, 2, 2, 1, -3.5f, -1, 0.5f, (float) (Math.PI / 2), 0, 0);
        ModelUtil.addCube(pd, "wand", 98, 97, -2.5f, -0.5f, -14.5f, 1, 1, 6, -3.5f, -1.5f, 0.5f, (float) (Math.PI / 2), 0, 0);
        ModelUtil.addCube(pd, "upper_left_arm", 103, 68, 0, -2.5f, -2, 4, 5, 4, 4.5f, -1, 0.5f, -(float) (Math.PI / 4), 0, 0);
        ModelUtil.addCube(pd, "lower_left_arm", 86, 68, -2.5f, -2.0f, -2.0f, 4, 5, 4, 6.5f, 2.5355f, -3.0355f, 0, (float) (Math.PI / 4), (float) (Math.PI / 2));
        ModelUtil.addCube(pd, "left_hand", 113, 78, -2, 3, -2.5f, 1, 2, 2, 4.5f, 0.5f, 2, -(float) (Math.PI / 4), 0, 0);
        ModelUtil.addCube(pd, "book", 91, 120, -1.5f, -3, -3.5f, 4, 6, 2, 0, 1.5f, 0);
        ModelUtil.addCube(pd, "robe_top", 104, 83, -3.5f, -2, -1.5f, 8, 4, 4, 0, 6.5f, 0);
        ModelUtil.addCube(pd, "robe_front", 110, 105, -3.5f, -4.5f, -1.5f, 8, 9, 1, 0, 13, 0);
        ModelUtil.addCube(pd, "right_leg", 120, 68, -1, 0, -1.1f, 2, 12, 2, -1.5f, 8.5f, 1.5f, (float) (Math.PI / 18), 0, 0);
        ModelUtil.addCube(pd, "robe_back_right", 88, 105, -2, 0.4f, -0.6f, 4, 9, 1, -1.5f, 8, 2, (float) (Math.PI / 18), 0, 0);
        ModelUtil.addCube(pd, "robe_right", 113, 92, -7.501f, -0.6f, -1.35f, 1, 9, 3, 4, 9, 0.5f, (float) (Math.PI / 36), 0, 0);
        ModelUtil.addCube(pd, "left_leg", 120, 68, -1, 0, -1.1f, 2, 12, 2, 2.5f, 8.5f, 0.5f, (float) (Math.PI / 18), 0, 0);
        ModelUtil.addCube(pd, "robe_back_left", 99, 105, 2, 0.4f, -0.6f, 4, 9, 1, -1.5f, 8, 2, (float) (Math.PI / 18), 0, 0);
        ModelUtil.addCube(pd, "robe_left", 122, 93, -0.499f, -0.6f, -0.85f, 1, 9, 2, 4, 9, 0.5f, (float) (Math.PI / 36), 0, 0);
        return LayerDefinition.create(md, 128, 128);
    }

    @Override
    public void setupAnim(ArcaneGuardian entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        float pitch = headPitch * (float) Math.PI / 180f;
        float yaw = netHeadYaw * (float) Math.PI / 180f;
        head.xRot = pitch;
        head.yRot = yaw;
        hoodTop.xRot = pitch;
        hoodTop.yRot = yaw;
        hoodLeft.xRot = pitch;
        hoodLeft.yRot = yaw;
        hoodRight.xRot = pitch;
        hoodRight.yRot = yaw;
        hoodBack.xRot = pitch;
        hoodBack.yRot = yaw;
        float y = 45 * (Mth.cos(ageInTicks % 360 * (float) Math.PI / 45f) - Mth.cos((ageInTicks - 1) % 360 * (float) Math.PI / 45f));
        head.y = -4.5f + y;
        neck.y = -4 + y;
        hoodTop.y = -4.5f + y;
        hoodLeft.y = -4.5f + y;
        hoodRight.y = -4.5f + y;
        hoodBack.y = -4.5f + y;
        body.y = -1.5f + y;
        rod.y = 2.5f + y;
        rod1.y = 2.5f + y;
        rod2.y = 2.5f + y;
        rod3.y = 2.5f + y;
        rod4.y = 2.5f + y;
        upperRightArm.y = -1 + y;
        lowerRightArm.y = -1 + y;
        rightHand.y = -1 + y;
        wand.y = -1.5f + y;
        upperLeftArm.y = -1 + y;
        lowerLeftArm.y = 2.5355f + y;
        leftHand.y = 0.5f + y;
        book.y = 1.5f + y;
        robeTop.y = 6.5f + y;
        robeFront.y = 13 + y;
        rightLeg.y = 8.5f + y;
        robeBackRight.y = 8 + y;
        robeRight.y = 9 + y;
        leftLeg.y = 8.5f + y;
        robeBackLeft.y = 8 + y;
        robeLeft.y = 9 + y;
        rune.zRot = (float) ((ageInTicks % 360) * Math.PI / 180);
        float swing = Mth.cos((ageInTicks % 360) * 0.1f) * 0.05f + 0.05f;
        upperRightArm.zRot = swing;
        lowerRightArm.zRot = swing;
        rightHand.zRot = swing;
        wand.zRot = swing;
    }

    @Override
    public void renderToBuffer(PoseStack poseStack, VertexConsumer buffer, int packedLight, int packedOverlay, float red, float green, float blue, float alpha) {
        head.render(poseStack, buffer, packedLight, packedOverlay);
        neck.render(poseStack, buffer, packedLight, packedOverlay);
        hoodTop.render(poseStack, buffer, packedLight, packedOverlay);
        hoodLeft.render(poseStack, buffer, packedLight, packedOverlay);
        hoodRight.render(poseStack, buffer, packedLight, packedOverlay);
        hoodBack.render(poseStack, buffer, packedLight, packedOverlay);
        body.render(poseStack, buffer, packedLight, packedOverlay);
        rune.render(poseStack, buffer, packedLight, packedOverlay);
        rod.render(poseStack, buffer, packedLight, packedOverlay);
        rod1.render(poseStack, buffer, packedLight, packedOverlay);
        rod2.render(poseStack, buffer, packedLight, packedOverlay);
        rod3.render(poseStack, buffer, packedLight, packedOverlay);
        rod4.render(poseStack, buffer, packedLight, packedOverlay);
        upperRightArm.render(poseStack, buffer, packedLight, packedOverlay);
        lowerRightArm.render(poseStack, buffer, packedLight, packedOverlay);
        rightHand.render(poseStack, buffer, packedLight, packedOverlay);
        wand.render(poseStack, buffer, packedLight, packedOverlay);
        upperLeftArm.render(poseStack, buffer, packedLight, packedOverlay);
        lowerLeftArm.render(poseStack, buffer, packedLight, packedOverlay);
        leftHand.render(poseStack, buffer, packedLight, packedOverlay);
        book.render(poseStack, buffer, packedLight, packedOverlay);
        robeTop.render(poseStack, buffer, packedLight, packedOverlay);
        robeFront.render(poseStack, buffer, packedLight, packedOverlay);
        rightLeg.render(poseStack, buffer, packedLight, packedOverlay);
        robeBackRight.render(poseStack, buffer, packedLight, packedOverlay);
        robeRight.render(poseStack, buffer, packedLight, packedOverlay);
        leftLeg.render(poseStack, buffer, packedLight, packedOverlay);
        robeBackLeft.render(poseStack, buffer, packedLight, packedOverlay);
        robeLeft.render(poseStack, buffer, packedLight, packedOverlay);
    }
}
