package com.github.minecraftschurlimods.arsmagicalegacy.client.model.entity;

import com.github.minecraftschurlimods.arsmagicalegacy.api.ArsMagicaAPI;
import com.github.minecraftschurlimods.arsmagicalegacy.common.entity.LightningGuardian;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.Mth;

public class LightningGuardianModel extends AMEntityModel<LightningGuardian> {
    public static final ModelLayerLocation LAYER_LOCATION = new ModelLayerLocation(new ResourceLocation(ArsMagicaAPI.MOD_ID, "lightning_guardian"), "main");
    private final ModelPart head;
    private final ModelPart chest;
    private final ModelPart body;
    private final ModelPart tail;
    private final ModelPart shoulder;
    private final ModelPart chestFront;
    private final ModelPart chestBack;
    private final ModelPart rightChest;
    private final ModelPart rightArm;
    private final ModelPart rightHand;
    private final ModelPart topRightHandFront;
    private final ModelPart topRightHandInside;
    private final ModelPart topRightHandBack;
    private final ModelPart bottomRightHandFront;
    private final ModelPart bottomRightHandInside;
    private final ModelPart bottomRightHandBack;
    private final ModelPart leftChest;
    private final ModelPart leftArm;
    private final ModelPart leftHand;
    private final ModelPart topLeftHandFront;
    private final ModelPart topLeftHandInside;
    private final ModelPart topLeftHandBack;
    private final ModelPart bottomLeftHandFront;
    private final ModelPart bottomLeftHandInside;
    private final ModelPart bottomLeftHandBack;

    public LightningGuardianModel(ModelPart root) {
        head = addPart(root, "head");
        chest = addPart(root, "chest");
        body = addPart(root, "body");
        tail = addPart(root, "tail");
        shoulder = addPart(root, "shoulder");
        chestFront = addPart(root, "chest_front");
        chestBack = addPart(root, "chest_back");
        rightChest = addPart(root, "right_chest");
        rightArm = addPart(root, "right_arm");
        rightHand = addPart(root, "right_hand");
        topRightHandFront = addPart(root, "top_right_hand_front");
        topRightHandInside = addPart(root, "top_right_hand_inside");
        topRightHandBack = addPart(root, "top_right_hand_back");
        bottomRightHandFront = addPart(root, "bottom_right_hand_front");
        bottomRightHandInside = addPart(root, "bottom_right_hand_inside");
        bottomRightHandBack = addPart(root, "bottom_right_hand_back");
        leftChest = addPart(root, "left_chest");
        leftArm = addPart(root, "left_arm");
        leftHand = addPart(root, "left_hand");
        topLeftHandFront = addPart(root, "top_left_hand_front");
        topLeftHandInside = addPart(root, "top_left_hand_inside");
        topLeftHandBack = addPart(root, "top_left_hand_back");
        bottomLeftHandFront = addPart(root, "bottom_left_hand_front");
        bottomLeftHandInside = addPart(root, "bottom_left_hand_inside");
        bottomLeftHandBack = addPart(root, "bottom_left_hand_back");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition md = new MeshDefinition();
        PartDefinition pd = md.getRoot();
        addCube(pd, "head", 32, 0, -1.5f, -3, -1.5f, 3, 3, 3, 0, 7, 0);
        addCube(pd, "chest", 32, 6, -3.5f, -2, -2.5f, 7, 4, 5, 0, 9, 0);
        addCube(pd, "body", 44, 0, -2, -2, -1, 4, 4, 2, 0, 13, 0);
        addCube(pd, "tail", 56, 0, -1, -3, -0.5f, 2, 6, 1, 0, 18, 0);
        addCube(pd, "shoulder", 32, 17, -4, -1, -1, 8, 2, 2, 0, 7.999f, 0);
        addCube(pd, "chest_front", 0, 0, -3.5f, -1, -2.501f, 7, 5, 0, 0, 8, 0);
        addCube(pd, "chest_back", 0, 5, -3.5f, -2.5f, 2.501f, 7, 7, 0, 0, 6.5f, 0);
        addCube(pd, "right_chest", 0, 14, -2.5f, -3.5f, 0, 5, 7, 0, 3.501f, 8.5f, 0, 0, -(float) (Math.PI / 2), 0);
        addCube(pd, "right_arm", 32, 17, 0, -1, -1, 2, 13, 2, 4, 8, 0);
        addCube(pd, "right_hand", 14, 0, 2, 7, -1, 1, 4, 2, 4, 8, 0);
        addCube(pd, "top_right_hand_front", 14, 6, -1, 7, 1, 4, 1, 1, 4, 8, 0);
        addCube(pd, "top_right_hand_inside", 24, 6, -1, 7, -1, 1, 1, 2, 4, 8, 0);
        addCube(pd, "top_right_hand_back", 14, 8, -1, 7, -2, 4, 1, 1, 4, 8, 0);
        addCube(pd, "bottom_right_hand_front", 14, 10, -1, 10, 1, 4, 1, 1, 4, 8, 0);
        addCube(pd, "bottom_right_hand_inside", 24, 10, -1, 10, -1, 1, 1, 2, 4, 8, 0);
        addCube(pd, "bottom_right_hand_back", 14, 12, -1, 10, -2, 4, 1, 1, 4, 8, 0);
        addCube(pd, "left_chest", 0, 21, -2.5f, -3.5f, 0, 5, 7, 0, -3.501f, 8.5f, 0, 0, -(float) (Math.PI / 2), 0);
        addCube(pd, "left_arm", 40, 17, -2, -1, -1, 2, 13, 2, -4, 8, 0);
        addCube(pd, "left_hand", 20, 0, -3, 7, -1, 1, 4, 2, -4, 8, 0);
        addCube(pd, "top_left_hand_front", 14, 14, -3, 7, 1, 4, 1, 1, -4, 8, 0);
        addCube(pd, "top_left_hand_inside", 24, 14, 0, 7, -1, 1, 1, 2, -4, 8, 0);
        addCube(pd, "top_left_hand_back", 14, 16, -3, 7, -2, 4, 1, 1, -4, 8, 0);
        addCube(pd, "bottom_left_hand_front", 14, 18, -3, 10, 1, 4, 1, 1, -4, 8, 0);
        addCube(pd, "bottom_left_hand_inside", 24, 18, 0, 10, -1, 1, 1, 2, -4, 8, 0);
        addCube(pd, "bottom_left_hand_back", 14, 20, -3, 10, -2, 4, 1, 1, -4, 8, 0);
        return LayerDefinition.create(md, 64, 32);
    }

    @Override
    public void setupAnim(LightningGuardian entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        setHeadRotations(headPitch, netHeadYaw, head);
        float y = 45 * (Mth.cos(ageInTicks % 360 * (float) Math.PI / 45f) - Mth.cos((ageInTicks - 1) % 360 * (float) Math.PI / 45f));
        head.y = 7 + y;
        chest.y = 9 + y;
        body.y = 13 + y;
        tail.y = 18 + y;
        shoulder.y = 7.999f + y;
        chestFront.y = 8 + y;
        chestBack.y = 6.5f + y;
        rightChest.y = 8.5f + y;
        rightArm.y = 8 + y;
        rightHand.y = 8 + y;
        topRightHandFront.y = 8 + y;
        topRightHandInside.y = 8 + y;
        topRightHandBack.y = 8 + y;
        bottomRightHandFront.y = 8 + y;
        bottomRightHandInside.y = 8 + y;
        bottomRightHandBack.y = 8 + y;
        leftChest.y = 8.5f + y;
        leftArm.y = 8 + y;
        leftHand.y = 8 + y;
        topLeftHandFront.y = 8 + y;
        topLeftHandInside.y = 8 + y;
        topLeftHandBack.y = 8 + y;
        bottomLeftHandFront.y = 8 + y;
        bottomLeftHandInside.y = 8 + y;
        bottomLeftHandBack.y = 8 + y;
        float swing = Mth.cos(ageInTicks * 0.1f) * 0.05f + 0.05f;
        rightArm.zRot = -swing;
        rightHand.zRot = -swing;
        topRightHandFront.zRot = -swing;
        topRightHandInside.zRot = -swing;
        topRightHandBack.zRot = -swing;
        bottomRightHandFront.zRot = -swing;
        bottomRightHandInside.zRot = -swing;
        bottomRightHandBack.zRot = -swing;
        leftArm.zRot = swing;
        leftHand.zRot = swing;
        topLeftHandFront.zRot = swing;
        topLeftHandInside.zRot = swing;
        topLeftHandBack.zRot = swing;
        bottomLeftHandFront.zRot = swing;
        bottomLeftHandInside.zRot = swing;
        bottomLeftHandBack.zRot = swing;
    }
}
