@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.github.minecraftschurli.arsmagicalegacy.client.renderer;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
