package com.github.minecraftschurlimods.arsmagicalegacy.api.etherium;

import com.github.minecraftschurlimods.arsmagicalegacy.api.ArsMagicaApi;
import com.mojang.serialization.Codec;
import com.mojang.serialization.codecs.RecordCodecBuilder;
import net.minecraft.core.registries.Registries;
import net.minecraft.util.ExtraCodecs;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.neoforged.neoforge.registries.datamaps.DataMapType;
import org.jspecify.annotations.Nullable;

/// Represents an obelisk fuel.
///
/// @param burnTime        The burn time of the obelisk fuel, in ticks.
/// @param etheriumPerTick The etherium generated by the obelisk fuel each tick.
public record ObeliskFuel(int burnTime, int etheriumPerTick) {
    public static final Codec<ObeliskFuel> CODEC = RecordCodecBuilder.create(inst -> inst.group(
        ExtraCodecs.POSITIVE_INT.fieldOf("burn_time").forGetter(ObeliskFuel::burnTime),
        ExtraCodecs.POSITIVE_INT.fieldOf("etherium_per_tick").forGetter(ObeliskFuel::etheriumPerTick)
    ).apply(inst, ObeliskFuel::new));
    public static final DataMapType<Item, ObeliskFuel> DATA_MAP = DataMapType.builder(ArsMagicaApi.id("obelisk_fuel"), Registries.ITEM, CODEC)
        .synced(CODEC, true)
        .build();

    /// @return The total etherium that burning the obelisk fuel will generate.
    public int totalEtherium() {
        return burnTime * etheriumPerTick;
    }

    /// @param stack The [ItemStack] to get the [ObeliskFuel] for.
    /// @return The [ObeliskFuel] for the given [ItemStack], or null if no such [ObeliskFuel] exists.
    @Nullable
    public static ObeliskFuel getFuel(ItemStack stack) {
        return stack.typeHolder().getData(DATA_MAP);
    }

    /// @param stack The [ItemStack] to check.
    /// @return Whether the given [ItemStack] is an [ObeliskFuel] or not.
    public static boolean isFuel(ItemStack stack) {
        return getFuel(stack) != null;
    }
}
