package at.minecraftschurli.mods.arsmagicalegacy.init;

import at.minecraftschurli.mods.arsmagicalegacy.api.ArsMagicaApi;
import at.minecraftschurli.mods.arsmagicalegacy.api.etherium.EtheriumType;
import at.minecraftschurli.mods.arsmagicalegacy.api.magic.Affinity;
import at.minecraftschurli.mods.arsmagicalegacy.api.spell.Spell;
import at.minecraftschurli.mods.arsmagicalegacy.item.AMArmorItem;
import at.minecraftschurli.mods.arsmagicalegacy.item.AffinityTomeItem;
import at.minecraftschurli.mods.arsmagicalegacy.item.AirSledItem;
import at.minecraftschurli.mods.arsmagicalegacy.item.ArcaneSpellBookItem;
import at.minecraftschurli.mods.arsmagicalegacy.item.CrystalPhylacteryItem;
import at.minecraftschurli.mods.arsmagicalegacy.item.CrystalWrenchItem;
import at.minecraftschurli.mods.arsmagicalegacy.item.EarthArmorItem;
import at.minecraftschurli.mods.arsmagicalegacy.item.EnderBootsItem;
import at.minecraftschurli.mods.arsmagicalegacy.item.FireAntennaeItem;
import at.minecraftschurli.mods.arsmagicalegacy.item.HolderDataComponentItem;
import at.minecraftschurli.mods.arsmagicalegacy.item.InfinityOrbItem;
import at.minecraftschurli.mods.arsmagicalegacy.item.InscriptionTableUpgradeItem;
import at.minecraftschurli.mods.arsmagicalegacy.item.LifeWardItem;
import at.minecraftschurli.mods.arsmagicalegacy.item.LightningCharmItem;
import at.minecraftschurli.mods.arsmagicalegacy.item.ManaArmorItem;
import at.minecraftschurli.mods.arsmagicalegacy.item.NatureScytheItem;
import at.minecraftschurli.mods.arsmagicalegacy.item.RuneBagItem;
import at.minecraftschurli.mods.arsmagicalegacy.item.SpellBookItem;
import at.minecraftschurli.mods.arsmagicalegacy.item.SpellItem;
import at.minecraftschurli.mods.arsmagicalegacy.item.SpellRecipeItem;
import at.minecraftschurli.mods.arsmagicalegacy.item.WaterOrbsItem;
import at.minecraftschurli.mods.arsmagicalegacy.item.WintersGraspItem;
import at.minecraftschurli.mods.arsmagicalegacy.item.WizardsChalkItem;
import net.minecraft.core.Direction;
import net.minecraft.core.component.DataComponents;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.world.effect.MobEffectInstance;
import net.minecraft.world.entity.EquipmentSlot;
import net.minecraft.world.food.FoodProperties;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.BoatItem;
import net.minecraft.world.item.BucketItem;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.HangingSignItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemUseAnimation;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.PlaceOnWaterBlockItem;
import net.minecraft.world.item.SignItem;
import net.minecraft.world.item.SpawnEggItem;
import net.minecraft.world.item.StandingAndWallBlockItem;
import net.minecraft.world.item.component.Consumable;
import net.minecraft.world.item.component.ItemContainerContents;
import net.minecraft.world.item.consume_effects.ApplyStatusEffectsConsumeEffect;
import net.minecraft.world.item.equipment.ArmorType;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredRegister;

public interface AMItems {
    DeferredRegister.Items ITEMS = DeferredRegister.createItems(ArsMagicaApi.MOD_ID);
    // @formatter:off
    DeferredItem<SpellItem>                             SPELL                            = ITEMS.registerItem("spell", p -> new SpellItem(p.stacksTo(1).component(AMDataComponents.SPELL, Spell.EMPTY)));
    DeferredItem<SpellRecipeItem>                       SPELL_RECIPE                     = ITEMS.registerItem("spell_recipe", p -> new SpellRecipeItem(p.stacksTo(1).component(AMDataComponents.SPELL, Spell.EMPTY)));
    DeferredItem<HolderDataComponentItem<EtheriumType>> ETHERIUM_PLACEHOLDER             = ITEMS.registerItem("etherium_placeholder", p -> new HolderDataComponentItem<>(p, AMDataComponents.ETHERIUM_TYPE.get()));
    DeferredItem<BucketItem>                            LIQUID_ETHERIUM_BUCKET           = ITEMS.registerItem("liquid_etherium_bucket", p -> new BucketItem(AMFluids.LIQUID_ETHERIUM.get(), p.craftRemainder(Items.BUCKET).stacksTo(1)));
    DeferredItem<BlockItem>                             OCCULUS                          = ITEMS.registerSimpleBlockItem(AMBlocks.OCCULUS);
    DeferredItem<BlockItem>                             INSCRIPTION_TABLE                = ITEMS.registerSimpleBlockItem(AMBlocks.INSCRIPTION_TABLE);
    DeferredItem<InscriptionTableUpgradeItem>           INSCRIPTION_TABLE_UPGRADE_TIER_1 = ITEMS.registerItem("inscription_table_upgrade_tier_1", p -> new InscriptionTableUpgradeItem(p, 1));
    DeferredItem<InscriptionTableUpgradeItem>           INSCRIPTION_TABLE_UPGRADE_TIER_2 = ITEMS.registerItem("inscription_table_upgrade_tier_2", p -> new InscriptionTableUpgradeItem(p, 2));
    DeferredItem<InscriptionTableUpgradeItem>           INSCRIPTION_TABLE_UPGRADE_TIER_3 = ITEMS.registerItem("inscription_table_upgrade_tier_3", p -> new InscriptionTableUpgradeItem(p, 3));
    DeferredItem<BlockItem>                             ALTAR_CORE                       = ITEMS.registerSimpleBlockItem(AMBlocks.ALTAR_CORE);
    DeferredItem<BlockItem>                             MAGIC_WALL                       = ITEMS.registerSimpleBlockItem(AMBlocks.MAGIC_WALL);
    DeferredItem<BlockItem>                             OBELISK                          = ITEMS.registerSimpleBlockItem(AMBlocks.OBELISK);
    DeferredItem<BlockItem>                             CELESTIAL_PRISM                  = ITEMS.registerSimpleBlockItem(AMBlocks.CELESTIAL_PRISM);
    DeferredItem<BlockItem>                             BLACK_AUREM                      = ITEMS.registerSimpleBlockItem(AMBlocks.BLACK_AUREM);
    DeferredItem<CrystalWrenchItem>                     CRYSTAL_WRENCH                   = ITEMS.registerItem("crystal_wrench", p -> new CrystalWrenchItem(p.stacksTo(1)));
    DeferredItem<WizardsChalkItem>                      WIZARDS_CHALK                    = ITEMS.registerItem("wizards_chalk", p -> new WizardsChalkItem(AMBlocks.WIZARDS_CHALK.get(), p.stacksTo(1).durability(100)));
    DeferredItem<BlockItem>                             REDSTONE_INLAY                   = ITEMS.registerSimpleBlockItem(AMBlocks.REDSTONE_INLAY);
    DeferredItem<BlockItem>                             IRON_INLAY                       = ITEMS.registerSimpleBlockItem(AMBlocks.IRON_INLAY);
    DeferredItem<BlockItem>                             GOLD_INLAY                       = ITEMS.registerSimpleBlockItem(AMBlocks.GOLD_INLAY);
    DeferredItem<BlockItem>                             VINTEUM_TORCH                    = ITEMS.registerItem("vinteum_torch", p -> new StandingAndWallBlockItem(AMBlocks.VINTEUM_TORCH.get(), AMBlocks.VINTEUM_WALL_TORCH.get(), Direction.DOWN, p));
    DeferredItem<Item>                                  SPELL_PARCHMENT                  = ITEMS.registerSimpleItem("spell_parchment");
    DeferredItem<SpellBookItem>                         SPELL_BOOK                       = ITEMS.registerItem("spell_book", p -> new SpellBookItem(p.stacksTo(1).component(DataComponents.CONTAINER, ItemContainerContents.EMPTY).component(AMDataComponents.SELECTED_INDEX, 0)));
    DeferredItem<AMArmorItem>                           MAGITECH_GOGGLES                 = ITEMS.registerItem("magitech_goggles", p -> new AMArmorItem(p.durability(100), EquipmentSlot.HEAD, SoundEvents.ARMOR_EQUIP_LEATHER, AMArmorItem.MAGITECH_GOGGLES_ASSET_ID));
    DeferredItem<ManaArmorItem>                         MAGE_HELMET                      = ITEMS.registerItem("mage_helmet", p -> ManaArmorItem.mage(p, ArmorType.HELMET, 2));
    DeferredItem<ManaArmorItem>                         MAGE_CHESTPLATE                  = ITEMS.registerItem("mage_chestplate", p -> ManaArmorItem.mage(p, ArmorType.CHESTPLATE, 6));
    DeferredItem<ManaArmorItem>                         MAGE_LEGGINGS                    = ITEMS.registerItem("mage_leggings", p -> ManaArmorItem.mage(p, ArmorType.LEGGINGS, 4));
    DeferredItem<ManaArmorItem>                         MAGE_BOOTS                       = ITEMS.registerItem("mage_boots", p -> ManaArmorItem.mage(p, ArmorType.BOOTS, 2));
    DeferredItem<ManaArmorItem>                         BATTLEMAGE_HELMET                = ITEMS.registerItem("battlemage_helmet", p -> ManaArmorItem.battlemage(p, ArmorType.HELMET, 3));
    DeferredItem<ManaArmorItem>                         BATTLEMAGE_CHESTPLATE            = ITEMS.registerItem("battlemage_chestplate", p -> ManaArmorItem.battlemage(p, ArmorType.CHESTPLATE, 8));
    DeferredItem<ManaArmorItem>                         BATTLEMAGE_LEGGINGS              = ITEMS.registerItem("battlemage_leggings", p -> ManaArmorItem.battlemage(p, ArmorType.LEGGINGS, 6));
    DeferredItem<ManaArmorItem>                         BATTLEMAGE_BOOTS                 = ITEMS.registerItem("battlemage_boots", p -> ManaArmorItem.battlemage(p, ArmorType.BOOTS, 3));
    DeferredItem<Item>                                  MANA_CAKE                        = ITEMS.registerSimpleItem("mana_cake", p -> p.component(DataComponents.CONSUMABLE, Consumable.builder().onConsume(new ApplyStatusEffectsConsumeEffect(new MobEffectInstance(AMMobEffects.MANA_REGENERATION, 600))).build()).food(new FoodProperties.Builder().nutrition(3).saturationModifier(0.6f).alwaysEdible().build()));
    DeferredItem<Item>                                  MANA_MARTINI                     = ITEMS.registerSimpleItem("mana_martini", p -> p.component(DataComponents.CONSUMABLE, Consumable.builder().onConsume(new ApplyStatusEffectsConsumeEffect(new MobEffectInstance(AMMobEffects.BURNOUT_REDUCTION, 300))).hasConsumeParticles(false).animation(ItemUseAnimation.DRINK).sound(SoundEvents.GENERIC_DRINK).build()).usingConvertsTo(Items.GLASS_BOTTLE));
    DeferredItem<InfinityOrbItem>                       INFINITY_ORB                     = ITEMS.registerItem("infinity_orb", InfinityOrbItem::new);
    DeferredItem<WaterOrbsItem>                         WATER_ORBS                       = ITEMS.registerItem("water_orbs", WaterOrbsItem::new);
    DeferredItem<FireAntennaeItem>                      FIRE_ANTENNAE                    = ITEMS.registerItem("fire_antennae", FireAntennaeItem::new);
    DeferredItem<EarthArmorItem>                        EARTH_ARMOR                      = ITEMS.registerItem("earth_armor", EarthArmorItem::new);
    DeferredItem<AirSledItem>                           AIR_SLED                         = ITEMS.registerItem("air_sled", AirSledItem::new);
    DeferredItem<WintersGraspItem>                      WINTERS_GRASP                    = ITEMS.registerItem("winters_grasp", WintersGraspItem::new);
    DeferredItem<LightningCharmItem>                    LIGHTNING_CHARM                  = ITEMS.registerItem("lightning_charm", LightningCharmItem::new);
    DeferredItem<NatureScytheItem>                      NATURE_SCYTHE                    = ITEMS.registerItem("nature_scythe", NatureScytheItem::new);
    DeferredItem<LifeWardItem>                          LIFE_WARD                        = ITEMS.registerItem("life_ward", LifeWardItem::new);
    DeferredItem<ArcaneSpellBookItem>                   ARCANE_SPELL_BOOK                = ITEMS.registerItem("arcane_spell_book", ArcaneSpellBookItem::new);
    DeferredItem<EnderBootsItem>                        ENDER_BOOTS                      = ITEMS.registerItem("ender_boots", EnderBootsItem::new);
    DeferredItem<HolderDataComponentItem<Affinity>>     AFFINITY_ESSENCE                 = ITEMS.registerItem("affinity_essence", p -> new HolderDataComponentItem<>(p, AMDataComponents.AFFINITY.get()));
    DeferredItem<AffinityTomeItem>                      AFFINITY_TOME                    = ITEMS.registerItem("affinity_tome", AffinityTomeItem::new);
    DeferredItem<Item>                                  BLANK_RUNE                       = ITEMS.registerSimpleItem("blank_rune");
    DeferredItem<Item>                                  WHITE_RUNE                       = ITEMS.registerSimpleItem("white_rune");
    DeferredItem<Item>                                  ORANGE_RUNE                      = ITEMS.registerSimpleItem("orange_rune");
    DeferredItem<Item>                                  MAGENTA_RUNE                     = ITEMS.registerSimpleItem("magenta_rune");
    DeferredItem<Item>                                  LIGHT_BLUE_RUNE                  = ITEMS.registerSimpleItem("light_blue_rune");
    DeferredItem<Item>                                  YELLOW_RUNE                      = ITEMS.registerSimpleItem("yellow_rune");
    DeferredItem<Item>                                  LIME_RUNE                        = ITEMS.registerSimpleItem("lime_rune");
    DeferredItem<Item>                                  PINK_RUNE                        = ITEMS.registerSimpleItem("pink_rune");
    DeferredItem<Item>                                  GRAY_RUNE                        = ITEMS.registerSimpleItem("gray_rune");
    DeferredItem<Item>                                  LIGHT_GRAY_RUNE                  = ITEMS.registerSimpleItem("light_gray_rune");
    DeferredItem<Item>                                  CYAN_RUNE                        = ITEMS.registerSimpleItem("cyan_rune");
    DeferredItem<Item>                                  PURPLE_RUNE                      = ITEMS.registerSimpleItem("purple_rune");
    DeferredItem<Item>                                  BLUE_RUNE                        = ITEMS.registerSimpleItem("blue_rune");
    DeferredItem<Item>                                  BROWN_RUNE                       = ITEMS.registerSimpleItem("brown_rune");
    DeferredItem<Item>                                  GREEN_RUNE                       = ITEMS.registerSimpleItem("green_rune");
    DeferredItem<Item>                                  RED_RUNE                         = ITEMS.registerSimpleItem("red_rune");
    DeferredItem<Item>                                  BLACK_RUNE                       = ITEMS.registerSimpleItem("black_rune");
    DeferredItem<RuneBagItem>                           RUNE_BAG                         = ITEMS.registerItem("rune_bag", p -> new RuneBagItem(p.stacksTo(1)));
    DeferredItem<BlockItem>                             CHIMERITE_ORE                    = ITEMS.registerSimpleBlockItem(AMBlocks.CHIMERITE_ORE);
    DeferredItem<BlockItem>                             DEEPSLATE_CHIMERITE_ORE          = ITEMS.registerSimpleBlockItem(AMBlocks.DEEPSLATE_CHIMERITE_ORE);
    DeferredItem<Item>                                  CHIMERITE                        = ITEMS.registerSimpleItem("chimerite");
    DeferredItem<BlockItem>                             CHIMERITE_BLOCK                  = ITEMS.registerSimpleBlockItem(AMBlocks.CHIMERITE_BLOCK);
    DeferredItem<BlockItem>                             TOPAZ_ORE                        = ITEMS.registerSimpleBlockItem(AMBlocks.TOPAZ_ORE);
    DeferredItem<BlockItem>                             DEEPSLATE_TOPAZ_ORE              = ITEMS.registerSimpleBlockItem(AMBlocks.DEEPSLATE_TOPAZ_ORE);
    DeferredItem<Item>                                  TOPAZ                            = ITEMS.registerSimpleItem("topaz");
    DeferredItem<BlockItem>                             TOPAZ_BLOCK                      = ITEMS.registerSimpleBlockItem(AMBlocks.TOPAZ_BLOCK);
    DeferredItem<BlockItem>                             VINTEUM_ORE                      = ITEMS.registerSimpleBlockItem(AMBlocks.VINTEUM_ORE);
    DeferredItem<BlockItem>                             DEEPSLATE_VINTEUM_ORE            = ITEMS.registerSimpleBlockItem(AMBlocks.DEEPSLATE_VINTEUM_ORE);
    DeferredItem<Item>                                  VINTEUM_DUST                     = ITEMS.registerSimpleItem("vinteum_dust");
    DeferredItem<BlockItem>                             VINTEUM_BLOCK                    = ITEMS.registerSimpleBlockItem(AMBlocks.VINTEUM_BLOCK);
    DeferredItem<BlockItem>                             MOONSTONE_ORE                    = ITEMS.registerSimpleBlockItem(AMBlocks.MOONSTONE_ORE);
    DeferredItem<BlockItem>                             DEEPSLATE_MOONSTONE_ORE          = ITEMS.registerSimpleBlockItem(AMBlocks.DEEPSLATE_MOONSTONE_ORE);
    DeferredItem<Item>                                  MOONSTONE                        = ITEMS.registerSimpleItem("moonstone");
    DeferredItem<BlockItem>                             MOONSTONE_BLOCK                  = ITEMS.registerSimpleBlockItem(AMBlocks.MOONSTONE_BLOCK);
    DeferredItem<BlockItem>                             SUNSTONE_ORE                     = ITEMS.registerSimpleBlockItem(AMBlocks.SUNSTONE_ORE);
    DeferredItem<Item>                                  SUNSTONE                         = ITEMS.registerSimpleItem("sunstone");
    DeferredItem<BlockItem>                             SUNSTONE_BLOCK                   = ITEMS.registerSimpleBlockItem(AMBlocks.SUNSTONE_BLOCK);
    DeferredItem<Item>                                  ARCANE_COMPOUND                  = ITEMS.registerSimpleItem("arcane_compound");
    DeferredItem<Item>                                  ARCANE_ASH                       = ITEMS.registerSimpleItem("arcane_ash");
    DeferredItem<Item>                                  PURIFIED_VINTEUM_DUST            = ITEMS.registerSimpleItem("purified_vinteum_dust");
    DeferredItem<BlockItem>                             WITCHWOOD_LOG                    = ITEMS.registerSimpleBlockItem(AMBlocks.WITCHWOOD_LOG);
    DeferredItem<BlockItem>                             WITCHWOOD                        = ITEMS.registerSimpleBlockItem(AMBlocks.WITCHWOOD_WOOD);
    DeferredItem<BlockItem>                             STRIPPED_WITCHWOOD_LOG           = ITEMS.registerSimpleBlockItem(AMBlocks.STRIPPED_WITCHWOOD_LOG);
    DeferredItem<BlockItem>                             STRIPPED_WITCHWOOD               = ITEMS.registerSimpleBlockItem(AMBlocks.STRIPPED_WITCHWOOD_WOOD);
    DeferredItem<BlockItem>                             WITCHWOOD_LEAVES                 = ITEMS.registerSimpleBlockItem(AMBlocks.WITCHWOOD_LEAVES);
    DeferredItem<BlockItem>                             WITCHWOOD_SAPLING                = ITEMS.registerSimpleBlockItem(AMBlocks.WITCHWOOD_SAPLING);
    DeferredItem<BlockItem>                             WITCHWOOD_PLANKS                 = ITEMS.registerSimpleBlockItem(AMBlocks.WITCHWOOD_PLANKS);
    DeferredItem<BlockItem>                             WITCHWOOD_SLAB                   = ITEMS.registerSimpleBlockItem(AMBlocks.WITCHWOOD_SLAB);
    DeferredItem<BlockItem>                             WITCHWOOD_STAIRS                 = ITEMS.registerSimpleBlockItem(AMBlocks.WITCHWOOD_STAIRS);
    DeferredItem<BlockItem>                             WITCHWOOD_FENCE                  = ITEMS.registerSimpleBlockItem(AMBlocks.WITCHWOOD_FENCE);
    DeferredItem<BlockItem>                             WITCHWOOD_FENCE_GATE             = ITEMS.registerSimpleBlockItem(AMBlocks.WITCHWOOD_FENCE_GATE);
    DeferredItem<BlockItem>                             WITCHWOOD_DOOR                   = ITEMS.registerItem("witchwood_door", p -> new DoubleHighBlockItem(AMBlocks.WITCHWOOD_DOOR.get(), p));
    DeferredItem<BlockItem>                             WITCHWOOD_TRAPDOOR               = ITEMS.registerSimpleBlockItem(AMBlocks.WITCHWOOD_TRAPDOOR);
    DeferredItem<BlockItem>                             WITCHWOOD_BUTTON                 = ITEMS.registerSimpleBlockItem(AMBlocks.WITCHWOOD_BUTTON);
    DeferredItem<BlockItem>                             WITCHWOOD_PRESSURE_PLATE         = ITEMS.registerSimpleBlockItem(AMBlocks.WITCHWOOD_PRESSURE_PLATE);
    DeferredItem<BlockItem>                             WITCHWOOD_SIGN                   = ITEMS.registerItem("witchwood_sign", p -> new SignItem(AMBlocks.WITCHWOOD_SIGN.get(), AMBlocks.WITCHWOOD_WALL_SIGN.get(), p.stacksTo(16)));
    DeferredItem<BlockItem>                             WITCHWOOD_HANGING_SIGN           = ITEMS.registerItem("witchwood_hanging_sign", p -> new HangingSignItem(AMBlocks.WITCHWOOD_HANGING_SIGN.get(), AMBlocks.WITCHWOOD_WALL_HANGING_SIGN.get(), p.stacksTo(16)));
    DeferredItem<BoatItem>                              WITCHWOOD_BOAT                   = ITEMS.registerItem("witchwood_boat", p -> new BoatItem(AMEntities.WITCHWOOD_BOAT.get(), p));
    DeferredItem<BoatItem>                              WITCHWOOD_CHEST_BOAT             = ITEMS.registerItem("witchwood_chest_boat", p -> new BoatItem(AMEntities.WITCHWOOD_CHEST_BOAT.get(), p));
    DeferredItem<BlockItem>                             AUM                              = ITEMS.registerSimpleBlockItem(AMBlocks.AUM);
    DeferredItem<BlockItem>                             CERUBLOSSOM                      = ITEMS.registerSimpleBlockItem(AMBlocks.CERUBLOSSOM);
    DeferredItem<BlockItem>                             DESERT_NOVA                      = ITEMS.registerSimpleBlockItem(AMBlocks.DESERT_NOVA);
    DeferredItem<BlockItem>                             TARMA_ROOT                       = ITEMS.registerSimpleBlockItem(AMBlocks.TARMA_ROOT);
    DeferredItem<BlockItem>                             WAKEBLOOM                        = ITEMS.registerItem("wakebloom", p -> new PlaceOnWaterBlockItem(AMBlocks.WAKEBLOOM.get(), p));
    DeferredItem<SpawnEggItem>                          DRYAD_SPAWN_EGG                  = ITEMS.registerItem("dryad_spawn_egg", SpawnEggItem::new, p -> p.spawnEgg(AMEntities.DRYAD.get()));
    DeferredItem<SpawnEggItem>                          MANA_CREEPER_SPAWN_EGG           = ITEMS.registerItem("mana_creeper_spawn_egg", SpawnEggItem::new, p -> p.spawnEgg(AMEntities.MANA_CREEPER.get()));
    DeferredItem<SpawnEggItem>                          WATER_GUARDIAN_SPAWN_EGG         = ITEMS.registerItem("water_guardian_spawn_egg", SpawnEggItem::new, p -> p.spawnEgg(AMEntities.WATER_GUARDIAN.get()));
    DeferredItem<SpawnEggItem>                          FIRE_GUARDIAN_SPAWN_EGG          = ITEMS.registerItem("fire_guardian_spawn_egg", SpawnEggItem::new, p -> p.spawnEgg(AMEntities.FIRE_GUARDIAN.get()));
    DeferredItem<SpawnEggItem>                          EARTH_GUARDIAN_SPAWN_EGG         = ITEMS.registerItem("earth_guardian_spawn_egg", SpawnEggItem::new, p -> p.spawnEgg(AMEntities.EARTH_GUARDIAN.get()));
    DeferredItem<SpawnEggItem>                          AIR_GUARDIAN_SPAWN_EGG           = ITEMS.registerItem("air_guardian_spawn_egg", SpawnEggItem::new, p -> p.spawnEgg(AMEntities.AIR_GUARDIAN.get()));
    DeferredItem<SpawnEggItem>                          ICE_GUARDIAN_SPAWN_EGG           = ITEMS.registerItem("ice_guardian_spawn_egg", SpawnEggItem::new, p -> p.spawnEgg(AMEntities.ICE_GUARDIAN.get()));
    DeferredItem<SpawnEggItem>                          LIGHTNING_GUARDIAN_SPAWN_EGG     = ITEMS.registerItem("lightning_guardian_spawn_egg", SpawnEggItem::new, p -> p.spawnEgg(AMEntities.LIGHTNING_GUARDIAN.get()));
    DeferredItem<SpawnEggItem>                          NATURE_GUARDIAN_SPAWN_EGG        = ITEMS.registerItem("nature_guardian_spawn_egg", SpawnEggItem::new, p -> p.spawnEgg(AMEntities.NATURE_GUARDIAN.get()));
    DeferredItem<SpawnEggItem>                          LIFE_GUARDIAN_SPAWN_EGG          = ITEMS.registerItem("life_guardian_spawn_egg", SpawnEggItem::new, p -> p.spawnEgg(AMEntities.LIFE_GUARDIAN.get()));
    DeferredItem<SpawnEggItem>                          ARCANE_GUARDIAN_SPAWN_EGG        = ITEMS.registerItem("arcane_guardian_spawn_egg", SpawnEggItem::new, p -> p.spawnEgg(AMEntities.ARCANE_GUARDIAN.get()));
    DeferredItem<SpawnEggItem>                          ENDER_GUARDIAN_SPAWN_EGG         = ITEMS.registerItem("ender_guardian_spawn_egg", SpawnEggItem::new, p -> p.spawnEgg(AMEntities.ENDER_GUARDIAN.get()));
    DeferredItem<CrystalPhylacteryItem>                 CRYSTAL_PHYLACTERY               = ITEMS.registerItem("crystal_phylactery", p -> new CrystalPhylacteryItem(p.stacksTo(1)));
    // @formatter:on
}
