package at.minecraftschurli.mods.arsmagicalegacy.init;

import at.minecraftschurli.mods.arsmagicalegacy.api.ArsMagicaApi;
import at.minecraftschurli.mods.arsmagicalegacy.api.constants.AMRegistries;
import at.minecraftschurli.mods.arsmagicalegacy.api.constants.AMTranslations;
import at.minecraftschurli.mods.arsmagicalegacy.api.spell.Spell;
import at.minecraftschurli.mods.arsmagicalegacy.api.spell.SpellIngredient;
import at.minecraftschurli.mods.arsmagicalegacy.api.spell.SpellModifier;
import at.minecraftschurli.mods.arsmagicalegacy.api.spell.SpellPart;
import at.minecraftschurli.mods.arsmagicalegacy.api.spell.SpellStat;
import at.minecraftschurli.mods.arsmagicalegacy.api.spell.SpellStatModifier;
import at.minecraftschurli.mods.arsmagicalegacy.spell.ColorModifier;
import at.minecraftschurli.mods.arsmagicalegacy.spell.EtheriumSpellIngredient;
import at.minecraftschurli.mods.arsmagicalegacy.spell.ItemSpellIngredient;
import at.minecraftschurli.mods.arsmagicalegacy.spell.SpellModifiers;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.Attract;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.BanishRain;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.Blink;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.Blizzard;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.Charm;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.CreateWater;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.Damage;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.Dig;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.Disarm;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.Dispel;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.DivineIntervention;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.Drought;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.Effect;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.EnderIntervention;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.Explosion;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.FallingStar;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.FireRain;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.Fling;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.Forge;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.Frost;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.Grow;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.Harvest;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.Heal;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.Ignition;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.Knockback;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.LifeDrain;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.LifeTap;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.Light;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.ManaBlast;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.ManaDrain;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.MeltArmor;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.PlaceBlock;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.Plow;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.RandomTeleport;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.Recall;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.Repel;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.Rift;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.Storm;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.Summon;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.TimeManipulation;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.Transplace;
import at.minecraftschurli.mods.arsmagicalegacy.spell.component.WizardsAutumn;
import at.minecraftschurli.mods.arsmagicalegacy.spell.shape.AreaOfEffect;
import at.minecraftschurli.mods.arsmagicalegacy.spell.shape.Beam;
import at.minecraftschurli.mods.arsmagicalegacy.spell.shape.Chain;
import at.minecraftschurli.mods.arsmagicalegacy.spell.shape.Channel;
import at.minecraftschurli.mods.arsmagicalegacy.spell.shape.Contingency;
import at.minecraftschurli.mods.arsmagicalegacy.spell.shape.Projectile;
import at.minecraftschurli.mods.arsmagicalegacy.spell.shape.Rune;
import at.minecraftschurli.mods.arsmagicalegacy.spell.shape.Self;
import at.minecraftschurli.mods.arsmagicalegacy.spell.shape.Touch;
import at.minecraftschurli.mods.arsmagicalegacy.spell.shape.Wall;
import at.minecraftschurli.mods.arsmagicalegacy.spell.shape.Wave;
import at.minecraftschurli.mods.arsmagicalegacy.spell.shape.Zone;
import com.mojang.serialization.MapCodec;
import net.minecraft.network.syncher.EntityDataSerializer;
import net.minecraft.resources.Identifier;
import net.minecraft.world.clock.ClockTimeMarkers;
import net.minecraft.world.effect.MobEffects;
import net.minecraft.world.entity.player.Player;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.NeoForgeRegistries;

import java.util.Map;
import java.util.function.Supplier;

public interface AMSpells {
    DeferredRegister<MapCodec<? extends SpellIngredient>> SPELL_INGREDIENTS = DeferredRegister.create(AMRegistries.Keys.SPELL_INGREDIENT, ArsMagicaApi.MOD_ID);
    DeferredHolder<MapCodec<? extends SpellIngredient>, MapCodec<ItemSpellIngredient>> ITEM_SPELL_INGREDIENT = SPELL_INGREDIENTS.register("item", () -> ItemSpellIngredient.CODEC);
    DeferredHolder<MapCodec<? extends SpellIngredient>, MapCodec<EtheriumSpellIngredient>> ETHERIUM_SPELL_INGREDIENT = SPELL_INGREDIENTS.register("etherium", () -> EtheriumSpellIngredient.CODEC);

    DeferredRegister<EntityDataSerializer<?>> DATA_SERIALIZERS = DeferredRegister.create(NeoForgeRegistries.Keys.ENTITY_DATA_SERIALIZERS, ArsMagicaApi.MOD_ID);
    DeferredHolder<EntityDataSerializer<?>, EntityDataSerializer<Spell>> DATA_SERIALIZER = DATA_SERIALIZERS.register("spell", () -> EntityDataSerializer.forValueType(Spell.STREAM_CODEC));

    DeferredRegister<SpellPart> SPELL_PARTS = DeferredRegister.create(AMRegistries.Keys.SPELL_PART, ArsMagicaApi.MOD_ID);
    // @formatter:off
    SpellStat BOUNCE_STAT           = new SpellStat(ArsMagicaApi.id("bounce"));
    SpellStat DAMAGE_STAT           = new SpellStat(ArsMagicaApi.id("damage"), SpellStatModifier::add);
    SpellStat DISMEMBERING_STAT     = new SpellStat(ArsMagicaApi.id("dismembering"));
    SpellStat DURATION_STAT         = new SpellStat(ArsMagicaApi.id("duration"), SpellStatModifier::addMultipliedBase);
    SpellStat EFFECT_POWER_STAT     = new SpellStat(ArsMagicaApi.id("effect_power"));
    SpellStat FORTUNE_STAT          = new SpellStat(ArsMagicaApi.id("fortune"));
    SpellStat GRAVITY_STAT          = new SpellStat(ArsMagicaApi.id("gravity"));
    SpellStat HEALING_STAT          = new SpellStat(ArsMagicaApi.id("healing"), SpellStatModifier::addMultipliedBase);
    SpellStat MINING_POWER_STAT     = new SpellStat(ArsMagicaApi.id("mining_power"));
    SpellStat PIERCING_STAT         = new SpellStat(ArsMagicaApi.id("piercing"), SpellStatModifier::add);
    SpellStat RANGE_STAT            = new SpellStat(ArsMagicaApi.id("range"), SpellStatModifier::addMultipliedBase);
    SpellStat RUNE_POWER_STAT       = new SpellStat(ArsMagicaApi.id("rune_power"));
    SpellStat SILK_TOUCH_STAT       = new SpellStat(ArsMagicaApi.id("silk_touch"));
    SpellStat SPEED_STAT            = new SpellStat(ArsMagicaApi.id("speed"), SpellStatModifier::addMultipliedBase);
    SpellStat TARGET_NON_SOLID_STAT = new SpellStat(ArsMagicaApi.id("target_non_solid"));

    Identifier CONTINGENCY_DAMAGE_ID = ArsMagicaApi.id("damage");
    Identifier CONTINGENCY_DEATH_ID  = ArsMagicaApi.id("death");
    Identifier CONTINGENCY_FALL_ID   = ArsMagicaApi.id("fall");
    Identifier CONTINGENCY_FIRE_ID   = ArsMagicaApi.id("fire");
    Identifier CONTINGENCY_HEALTH_ID = ArsMagicaApi.id("health");

    DeferredHolder<SpellPart, AreaOfEffect> AREA_OF_EFFECT     = register("area_of_effect",     AreaOfEffect::new);
    DeferredHolder<SpellPart, Beam>         BEAM               = register("beam",               Beam::new);
    DeferredHolder<SpellPart, Chain>        CHAIN              = register("chain",              Chain::new);
    DeferredHolder<SpellPart, Channel>      CHANNEL            = register("channel",            Channel::new);
    DeferredHolder<SpellPart, Projectile>   PROJECTILE         = register("projectile",         Projectile::new);
    DeferredHolder<SpellPart, Rune>         RUNE               = register("rune",               Rune::new);
    DeferredHolder<SpellPart, Self>         SELF               = register("self",               Self::new);
    DeferredHolder<SpellPart, Touch>        TOUCH              = register("touch",              Touch::new);
    DeferredHolder<SpellPart, Wall>         WALL               = register("wall",               Wall::new);
    DeferredHolder<SpellPart, Wave>         WAVE               = register("wave",               Wave::new);
    DeferredHolder<SpellPart, Zone>         ZONE               = register("zone",               Zone::new);
    DeferredHolder<SpellPart, Contingency>  CONTINGENCY_DAMAGE = register("contingency_damage", () -> new Contingency(CONTINGENCY_DAMAGE_ID));
    DeferredHolder<SpellPart, Contingency>  CONTINGENCY_DEATH  = register("contingency_death",  () -> new Contingency(CONTINGENCY_DEATH_ID));
    DeferredHolder<SpellPart, Contingency>  CONTINGENCY_FALL   = register("contingency_fall",   () -> new Contingency(CONTINGENCY_FALL_ID));
    DeferredHolder<SpellPart, Contingency>  CONTINGENCY_FIRE   = register("contingency_fire",   () -> new Contingency(CONTINGENCY_FIRE_ID));
    DeferredHolder<SpellPart, Contingency>  CONTINGENCY_HEALTH = register("contingency_health", () -> new Contingency(CONTINGENCY_HEALTH_ID));

    DeferredHolder<SpellPart, Damage>             DROWNING_DAMAGE     = register("drowning_damage",     () -> new Damage(AMDamageTypes.SPELL_DROWNING));
    DeferredHolder<SpellPart, Damage>             FIRE_DAMAGE         = register("fire_damage",         () -> new Damage(AMDamageTypes.SPELL_FIRE));
    DeferredHolder<SpellPart, Damage>             FROST_DAMAGE        = register("frost_damage",        () -> new Damage(AMDamageTypes.SPELL_FROST));
    DeferredHolder<SpellPart, Damage>             LIGHTNING_DAMAGE    = register("lightning_damage",    () -> new Damage(AMDamageTypes.SPELL_LIGHTNING));
    DeferredHolder<SpellPart, Damage>             MAGIC_DAMAGE        = register("magic_damage",        () -> new Damage(AMDamageTypes.SPELL_MAGIC));
    DeferredHolder<SpellPart, Damage>             PHYSICAL_DAMAGE     = register("physical_damage",     () -> new Damage(caster -> caster instanceof Player ? AMDamageTypes.SPELL_PHYSICAL_PLAYER : AMDamageTypes.SPELL_PHYSICAL));
    DeferredHolder<SpellPart, Effect>             ABSORPTION          = register("absorption",          () -> new Effect(MobEffects.ABSORPTION));
    DeferredHolder<SpellPart, Effect>             BLINDNESS           = register("blindness",           () -> new Effect(MobEffects.BLINDNESS));
    DeferredHolder<SpellPart, Effect>             HASTE               = register("haste",               () -> new Effect(MobEffects.HASTE));
    DeferredHolder<SpellPart, Effect>             HEALTH_BOOST        = register("health_boost",        () -> new Effect(MobEffects.HEALTH_BOOST));
    DeferredHolder<SpellPart, Effect>             INVISIBILITY        = register("invisibility",        () -> new Effect(MobEffects.INVISIBILITY));
    DeferredHolder<SpellPart, Effect>             JUMP_BOOST          = register("jump_boost",          () -> new Effect(MobEffects.JUMP_BOOST));
    DeferredHolder<SpellPart, Effect>             LEVITATION          = register("levitation",          () -> new Effect(MobEffects.LEVITATION));
    DeferredHolder<SpellPart, Effect>             NAUSEA              = register("nausea",              () -> new Effect(MobEffects.NAUSEA));
    DeferredHolder<SpellPart, Effect>             NIGHT_VISION        = register("night_vision",        () -> new Effect(MobEffects.NIGHT_VISION));
    DeferredHolder<SpellPart, Effect>             REGENERATION        = register("regeneration",        () -> new Effect(MobEffects.REGENERATION));
    DeferredHolder<SpellPart, Effect>             RESISTANCE          = register("resistance",          () -> new Effect(MobEffects.RESISTANCE));
    DeferredHolder<SpellPart, Effect>             SLOWNESS            = register("slowness",            () -> new Effect(MobEffects.SLOWNESS));
    DeferredHolder<SpellPart, Effect>             SLOW_FALLING        = register("slow_falling",        () -> new Effect(MobEffects.SLOW_FALLING));
    DeferredHolder<SpellPart, Effect>             SWIFTNESS           = register("swiftness",           () -> new Effect(MobEffects.SPEED));
    DeferredHolder<SpellPart, Effect>             WATER_BREATHING     = register("water_breathing",     () -> new Effect(MobEffects.WATER_BREATHING));
    DeferredHolder<SpellPart, Effect>             ASTRAL_DISTORTION   = register("astral_distortion",   () -> new Effect(AMMobEffects.ASTRAL_DISTORTION));
    DeferredHolder<SpellPart, Effect>             ENTANGLE            = register("entangle",            () -> new Effect(AMMobEffects.ENTANGLE));
    DeferredHolder<SpellPart, Effect>             FLIGHT              = register("flight",              () -> new Effect(AMMobEffects.FLIGHT));
    DeferredHolder<SpellPart, Effect>             FURY                = register("fury",                () -> new Effect(AMMobEffects.FURY));
    DeferredHolder<SpellPart, Effect>             GRAVITY_WELL        = register("gravity_well",        () -> new Effect(AMMobEffects.GRAVITY_WELL));
    DeferredHolder<SpellPart, Effect>             REFLECT             = register("reflect",             () -> new Effect(AMMobEffects.REFLECT));
    DeferredHolder<SpellPart, Effect>             SCRAMBLE_SYNAPSES   = register("scramble_synapses",   () -> new Effect(AMMobEffects.SCRAMBLE_SYNAPSES));
    DeferredHolder<SpellPart, Effect>             SHRINK              = register("shrink",              () -> new Effect(AMMobEffects.SHRINK));
    DeferredHolder<SpellPart, Effect>             SILENCE             = register("silence",             () -> new Effect(AMMobEffects.SILENCE));
    DeferredHolder<SpellPart, Effect>             SWIFT_SWIM          = register("swift_swim",          () -> new Effect(AMMobEffects.SWIFT_SWIM));
    DeferredHolder<SpellPart, Effect>             TEMPORAL_ANCHOR     = register("temporal_anchor",     () -> new Effect(AMMobEffects.TEMPORAL_ANCHOR));
    DeferredHolder<SpellPart, Effect>             TRUE_SIGHT          = register("true_sight",          () -> new Effect(AMMobEffects.TRUE_SIGHT));
    DeferredHolder<SpellPart, Effect>             WATERY_GRAVE        = register("watery_grave",        () -> new Effect(AMMobEffects.WATERY_GRAVE));
    DeferredHolder<SpellPart, Harvest>            HARVEST             = register("harvest",             () -> new Harvest(false));
    DeferredHolder<SpellPart, Harvest>            REPLANT             = register("replant",             () -> new Harvest(true));
    DeferredHolder<SpellPart, TimeManipulation>   DAYLIGHT            = register("daylight",            () -> new TimeManipulation(ClockTimeMarkers.DAY, AMTranslations.SPELL_FAIL_COMPONENT_DAYLIGHT));
    DeferredHolder<SpellPart, TimeManipulation>   MOONRISE            = register("moonrise",            () -> new TimeManipulation(ClockTimeMarkers.NIGHT, AMTranslations.SPELL_FAIL_COMPONENT_MOONRISE));
    DeferredHolder<SpellPart, Attract>            ATTRACT             = register("attract",             Attract::new);
    DeferredHolder<SpellPart, BanishRain>         BANISH_RAIN         = register("banish_rain",         BanishRain::new);
    DeferredHolder<SpellPart, Blink>              BLINK               = register("blink",               Blink::new);
    DeferredHolder<SpellPart, Blizzard>           BLIZZARD            = register("blizzard",            Blizzard::new);
    DeferredHolder<SpellPart, Charm>              CHARM               = register("charm",               Charm::new);
    DeferredHolder<SpellPart, CreateWater>        CREATE_WATER        = register("create_water",        CreateWater::new);
    DeferredHolder<SpellPart, Dig>                DIG                 = register("dig",                 Dig::new);
    DeferredHolder<SpellPart, Disarm>             DISARM              = register("disarm",              Disarm::new);
    DeferredHolder<SpellPart, Dispel>             DISPEL              = register("dispel",              Dispel::new);
    DeferredHolder<SpellPart, DivineIntervention> DIVINE_INTERVENTION = register("divine_intervention", DivineIntervention::new);
    DeferredHolder<SpellPart, Drought>            DROUGHT             = register("drought",             Drought::new);
    DeferredHolder<SpellPart, EnderIntervention>  ENDER_INTERVENTION  = register("ender_intervention",  EnderIntervention::new);
    DeferredHolder<SpellPart, Explosion>          EXPLOSION           = register("explosion",           Explosion::new);
    DeferredHolder<SpellPart, FallingStar>        FALLING_STAR        = register("falling_star",        FallingStar::new);
    DeferredHolder<SpellPart, FireRain>           FIRE_RAIN           = register("fire_rain",           FireRain::new);
    DeferredHolder<SpellPart, Fling>              FLING               = register("fling",               Fling::new);
    DeferredHolder<SpellPart, Forge>              FORGE               = register("forge",               Forge::new);
    DeferredHolder<SpellPart, Frost>              FROST               = register("frost",               Frost::new);
    DeferredHolder<SpellPart, Grow>               GROW                = register("grow",                Grow::new);
    DeferredHolder<SpellPart, Heal>               HEAL                = register("heal",                Heal::new);
    DeferredHolder<SpellPart, Ignition>           IGNITION            = register("ignition",            Ignition::new);
    DeferredHolder<SpellPart, Knockback>          KNOCKBACK           = register("knockback",           Knockback::new);
    DeferredHolder<SpellPart, LifeDrain>          LIFE_DRAIN          = register("life_drain",          LifeDrain::new);
    DeferredHolder<SpellPart, LifeTap>            LIFE_TAP            = register("life_tap",            LifeTap::new);
    DeferredHolder<SpellPart, Light>              LIGHT               = register("light",               Light::new);
    DeferredHolder<SpellPart, ManaBlast>          MANA_BLAST          = register("mana_blast",          ManaBlast::new);
    DeferredHolder<SpellPart, ManaDrain>          MANA_DRAIN          = register("mana_drain",          ManaDrain::new);
    DeferredHolder<SpellPart, MeltArmor>          MELT_ARMOR          = register("melt_armor",          MeltArmor::new);
    DeferredHolder<SpellPart, PlaceBlock>         PLACE_BLOCK         = register("place_block",         PlaceBlock::new);
    DeferredHolder<SpellPart, Plow>               PLOW                = register("plow",                Plow::new);
    DeferredHolder<SpellPart, RandomTeleport>     RANDOM_TELEPORT     = register("random_teleport",     RandomTeleport::new);
    DeferredHolder<SpellPart, Recall>             RECALL              = register("recall",              Recall::new);
    DeferredHolder<SpellPart, Repel>              REPEL               = register("repel",               Repel::new);
    DeferredHolder<SpellPart, Rift>               RIFT                = register("rift",                Rift::new);
    DeferredHolder<SpellPart, Storm>              STORM               = register("storm",               Storm::new);
    DeferredHolder<SpellPart, Summon>             SUMMON              = register("summon",              Summon::new);
    DeferredHolder<SpellPart, Transplace>         TRANSPLACE          = register("transplace",          Transplace::new);
    DeferredHolder<SpellPart, WizardsAutumn>      WIZARDS_AUTUMN      = register("wizards_autumn",      WizardsAutumn::new);

    DeferredHolder<SpellPart, SpellModifier> BOUNCE           = register("bounce",           () -> new SpellModifier(Map.of(BOUNCE_STAT, SpellStatModifier.add(1))));
    DeferredHolder<SpellPart, SpellModifier> DAMAGE           = register("damage",           () -> new SpellModifier(Map.of(DAMAGE_STAT, SpellStatModifier.add(1))));
    DeferredHolder<SpellPart, SpellModifier> DISMEMBERING     = register("dismembering",     () -> new SpellModifier(Map.of(DISMEMBERING_STAT, SpellStatModifier.add(1))));
    DeferredHolder<SpellPart, SpellModifier> DURATION         = register("duration",         () -> new SpellModifier(Map.of(DURATION_STAT, SpellStatModifier.multiply(2))));
    DeferredHolder<SpellPart, SpellModifier> EFFECT_POWER     = register("effect_power",     () -> new SpellModifier(Map.of(EFFECT_POWER_STAT, SpellStatModifier.add(1))));
    DeferredHolder<SpellPart, SpellModifier> GRAVITY          = register("gravity",          () -> new SpellModifier(Map.of(GRAVITY_STAT, SpellStatModifier.add(1))));
    DeferredHolder<SpellPart, SpellModifier> HEALING          = register("healing",          () -> new SpellModifier(Map.of(HEALING_STAT, SpellStatModifier.multiply(2))));
    DeferredHolder<SpellPart, SpellModifier> LUNAR            = register("lunar",            () -> new SpellModifier(SpellModifiers.lunarStatModifiers()));
    DeferredHolder<SpellPart, SpellModifier> MINING_POWER     = register("mining_power",     () -> new SpellModifier(Map.of(MINING_POWER_STAT, SpellStatModifier.add(1))));
    DeferredHolder<SpellPart, SpellModifier> PIERCING         = register("piercing",         () -> new SpellModifier(Map.of(PIERCING_STAT, SpellStatModifier.add(1))));
    DeferredHolder<SpellPart, SpellModifier> PROSPERITY       = register("prosperity",       () -> new SpellModifier(Map.of(FORTUNE_STAT, SpellStatModifier.add(1))));
    DeferredHolder<SpellPart, SpellModifier> RANGE            = register("range",            () -> new SpellModifier(Map.of(RANGE_STAT, SpellStatModifier.multiply(2))));
    DeferredHolder<SpellPart, SpellModifier> RUNE_POWER       = register("rune_power",       () -> new SpellModifier(Map.of(RUNE_POWER_STAT, SpellStatModifier.add(1))));
    DeferredHolder<SpellPart, SpellModifier> SILK_TOUCH       = register("silk_touch",       () -> new SpellModifier(Map.of(SILK_TOUCH_STAT, SpellStatModifier.add(1))));
    DeferredHolder<SpellPart, SpellModifier> SOLAR            = register("solar",            () -> new SpellModifier(SpellModifiers.solarStatModifiers()));
    DeferredHolder<SpellPart, SpellModifier> TARGET_NON_SOLID = register("target_non_solid", () -> new SpellModifier(Map.of(TARGET_NON_SOLID_STAT, SpellStatModifier.add(1))));
    DeferredHolder<SpellPart, SpellModifier> VELOCITY         = register("velocity",         () -> new SpellModifier(Map.of(SPEED_STAT, SpellStatModifier.addMultipliedBase(0.5))));
    DeferredHolder<SpellPart, ColorModifier> COLOR            = register("color",            ColorModifier::new);
    // @formatter:on

    private static <T extends SpellPart> DeferredHolder<SpellPart, T> register(String name, Supplier<T> supplier) {
        return SPELL_PARTS.register(name, supplier);
    }
}
