name: "Build Testing jars"

on:
  workflow_dispatch:

jobs:
  build:
    uses: MinecraftschurliMods/.github/.github/workflows/build.yml@main
    with:
      upload-artifacts: true
      release-type: dev
