name: 'Build Commit'
on:
  push:
    branches:
      - 'version/[0-9]**'
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '.github/**'
    tags-ignore:
      - '[0-9]+.[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Setup Build
        run: chmod 777 gradlew
      - name: Build with Gradle
        id: build
        env:
          RELEASE_TYPE: snapshot
        run: ./gradlew setupGithubActions build
      - name: Create a Release
        id: create_release
        uses: meeDamian/github-release@v1.0.1
        with:
          draft: false
          prerelease: true
          gzip: false
          commitish: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.build.outputs.version }}
          name: ${{ steps.build.outputs.modid }}-${{ steps.build.outputs.version }}
          files: >
            build/libs/${{ steps.build.outputs.modid }}-${{ steps.build.outputs.version }}.jar
            build/libs/${{ steps.build.outputs.modid }}-${{ steps.build.outputs.version }}-api.jar
            build/libs/${{ steps.build.outputs.modid }}-${{ steps.build.outputs.version }}-sources.jar
