name: 'Build Commit'
on:
  push:
    branches:
      - 'version/[0-9]**'
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '.github/**'
    tags-ignore:
      - '[0-9]+.[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Setup Build
        run: chmod 777 gradlew
      - name: Build with Gradle
        id: build
        env:
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          RELEASE_TYPE: snapshot
        run: ./gradlew setupGithubActions build publish
