name: "Build Commit"

on:
  push:
    branches:
      - "version/[0-9]**"
    paths-ignore:
      - "*.md"
      - "LICENSE.md"
    tags-ignore:
      - "[0-9]+.[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    uses: MinecraftschurliMods/.github/.github/workflows/build.yml@main
    with:
      maven-url: ${{ vars.MAVEN_URL }}
      maven-user: ${{ vars.MAVEN_USER }}
      publish-to-maven: true
      datagen-folder: src/main/generated/
    secrets:
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
