name: "Build Commit"

on:
  push:
    branches:
      - "version/[0-9]**"
    paths-ignore:
      - "*.md"
      - "LICENSE.md"
      - ".github/**"
    tags-ignore:
      - "[0-9]+.[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    uses: MinecraftschurliMods/.github/.github/workflows/build.yml@main
    secrets:
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
    with:
      publish-to-maven: true
      datagen-folder: src/main/generated/
