name: Build PR

on:
  pull_request:
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '.github/**'
      - 'src/main/resources/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Setup Build
        run: chmod 777 gradlew
      - name: Build with Gradle
        id: build
        run: ./gradlew build
