name: "Build Release"

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/')
    uses: MinecraftschurliMods/.github/.github/workflows/build.yml@main
    with:
      upload-artifacts: true
      artifact-retention: 1
      publish-to-maven: true
    secrets:
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

  publish:
    needs:
      - build
    strategy:
      matrix:
        platform:
          - GitHub
          - CurseForge
          - Modrinth
    uses: MinecraftschurliMods/.github/.github/workflows/publish.yml@main
    with:
      platform: ${{ matrix.platform }}
      modid: ${{ needs.build.outputs.modid }}
      version: ${{ needs.build.outputs.version }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}

  post-release:
    name: Post Release
    runs-on: ubuntu-latest
    needs:
      - build
      - publish

    steps:
      - name: Test outputs
        run: |
          echo "modrinth-id: ${{ needs.publish.outputs.modrinth-id }}"
          echo "modrinth-version: ${{ needs.publish.outputs.modrinth-version }}"
          echo "modrinth-url: ${{ needs.publish.outputs.modrinth-url }}"
          echo "modrinth-files: ${{ needs.publish.outputs.modrinth-files }}"
          echo "curseforge-id: ${{ needs.publish.outputs.curseforge-id }}"
          echo "curseforge-version: ${{ needs.publish.outputs.curseforge-version }}"
          echo "curseforge-url: ${{ needs.publish.outputs.curseforge-url }}"
          echo "curseforge-files: ${{ needs.publish.outputs.curseforge-files }}"
          echo "github-repo: ${{ needs.publish.outputs.github-repo }}"
          echo "github-tag: ${{ needs.publish.outputs.github-tag }}"
          echo "github-url: ${{ needs.publish.outputs.github-url }}"
          echo "github-files: ${{ needs.publish.outputs.github-files }}"
          echo "modid: ${{ needs.build.outputs.modid }}"
          echo "version: ${{ needs.build.outputs.version }}"
          echo "summary: ${{ needs.build.outputs.summary }}"

#      - name: Post Release
#        uses: Minecraftschurli/post-release-action@main
#        with:
#          webhook-url: ${{ secrets.WEBHOOK_URL }}
#          webhook-name: "Ars Magica: Legacy"
#          webhook-avatar: "https://raw.githubusercontent.com/MinecraftschurliMods/Ars-Magica-Legacy/version/1.19.x/src/main/resources/logo_small.png"
#          webhook-title: "Version {version} of Ars Magica: Legacy released!"
#          webhook-message: ${{ needs.release.outputs.summary }}
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          readme-template: ".github/README_TEMPLATE.md"
#          version: ${{ needs.release.outputs.version }}
#          exclude-links-webhook: "GitHub"
#          published-to: ${{ needs.release.outputs.published-to }}
#          github-link: ${{ needs.release.outputs.github-link }}
#          modrinth-link: ${{ needs.release.outputs.modrinth-link }}
#          curseforge-link: ${{ needs.release.outputs.curseforge-link }}
