name: "Build Release"
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+"
jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Setup Build
        run: chmod 777 gradlew
      - name: Build with Gradle
        id: build
        env:
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: ./gradlew setupGithubActions build publish
      - name: Get Changelog
        id: changelog
        uses: juliangruber/read-file-action@v1
        with:
          path: ./changelog.md
      - name: Create a Release
        id: create_release
        uses: meeDamian/github-release@2.0
        with:
          draft: false
          gzip: false
          prerelease: false
          name: ${{ steps.build.outputs.modid }}-${{ steps.build.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: >
            build/libs/${{ steps.build.outputs.modid }}-${{ steps.build.outputs.version }}.jar
            build/libs/${{ steps.build.outputs.modid }}-${{ steps.build.outputs.version }}-api.jar
            build/libs/${{ steps.build.outputs.modid }}-${{ steps.build.outputs.version }}-sources.jar
            build/libs/${{ steps.build.outputs.modid }}-${{ steps.build.outputs.version }}-javadoc.jar
            build/libs/${{ steps.build.outputs.modid }}-${{ steps.build.outputs.version }}-deobf.jar
          body: >
             ${{ steps.changelog.outputs.content }}
      - name: CF upload
        id: cf_upload
        uses: itsmeow/curseforge-upload@master
        with:
          release_type: release
          game_endpoint: minecraft
          token: ${{ secrets.CF_API_TOKEN }}
          project_id: ${{ steps.build.outputs.project_id }}
          game_versions: ${{ steps.build.outputs.curse_versions }}
          file_path: build/libs/${{ steps.build.outputs.modid }}-${{ steps.build.outputs.version }}.jar
          changelog_type: markdown
          changelog: ${{ steps.changelog.outputs.content }}
          relations: ${{ steps.build.outputs.curse_relations }}
