name: "Build Release"
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Setup Build
        run: chmod 777 gradlew
      - name: Build with Gradle
        id: build
        env:
          MAVEN_PASSWORD: ${{secrets.MAVEN_PASSWORD}}
          MAVEN_URL: ${{secrets.MAVEN_URL}}
          MAVEN_USER: ${{secrets.MAVEN_USER}}
        run: ./gradlew setupGithubActions build publish
      - name: Create a Release
        id: create_release
        uses: meeDamian/github-release@v1.0.1
        with:
          draft: false
          gzip: false
          prerelease: false
          name: ${{ steps.build.outputs.modid }}-${{ steps.build.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: >
            build/libs/${{ steps.build.outputs.modid }}-${{ steps.build.outputs.version }}.jar
            build/libs/${{ steps.build.outputs.modid }}-${{ steps.build.outputs.version }}-api.jar
            build/libs/${{ steps.build.outputs.modid }}-${{ steps.build.outputs.version }}-sources.jar
      - name: CF upload
        uses: itsmeow/curseforge-upload@master
        with:
          release_type: release
          game_endpoint: minecraft
          token: ${{ secrets.CF_API_TOKEN }}
          project_id: ${{ steps.build.outputs.project_id }}
          game_versions: ${{ steps.build.outputs.curse_versions }}
          file_path: build/libs/${{ steps.build.outputs.modid }}-${{ steps.build.outputs.version }}.jar
          changelog: >
            Changelog not added yet...
