name: "Build Release"
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+"
jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    strategy:
      matrix:
        version: [ 17 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.version }}
          distribution: 'adopt'
      - name: Setup Build
        run: chmod 777 gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        id: build
        env:
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          RELEASE_TYPE: release
        with:
          arguments: setupGithubActions build publish
      - name: Upload
        id: upload
        uses: Minecraftschurli/mc-publish@master
        with:
          java: ${{ matrix.version }}
          files: build/libs/!(*-@(all|api|deobf|slim|sources|javadoc)).jar
          github-files-primary: build/libs/!(*-@(all|api|deobf|slim|sources|javadoc)).jar
          github-files-secondary: build/libs/*-@(all|api|deobf|slim|sources|javadoc).jar
          changelog-file: changelog.md
          name: ${{ steps.build.outputs.modid }}-${{ steps.build.outputs.version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-token: ${{ secrets.CF_API_TOKEN }}
      - name: Read summary
        id: summary
        uses: juliangruber/read-file-action@v1
        with:
          path: summary.txt
      - name: Post Release
        uses: Minecraftschurli/mc-post-release@master
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          webhook-name: "Ars Magica: Legacy"
          webhook-avatar: "https://raw.githubusercontent.com/MinecraftschurliMods/Ars-Magica-Legacy/version/1.19.x/src/main/resources/logo_small.png"
          webhook-title: "Version {version} of Ars Magica: Legacy released!"
          webhook-message: "${{ steps.summary.outputs.content }}"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          readme-template: ".github/README_TEMPLATE.md"
          version: ${{ steps.build.outputs.version }}
          exclude-links-webhook: "GitHub"
          published-to: ${{ steps.upload.outputs.published-to }}
          github-link: ${{ steps.upload.outputs.github-link }}
          modrinth-link: ${{ steps.upload.outputs.modrinth-link }}
          curseforge-link: ${{ steps.upload.outputs.curseforge-link }}
