name: "Build Release"

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/')
    uses: MinecraftschurliMods/.github/.github/workflows/build.yml@main
    secrets:
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
    with:
      upload-artifacts: true
      artifact-retention: 1
      publish-to-maven: true
      release-type: release
      datagen-folder: src/main/generated/

  publish:
    needs:
      - build
    strategy:
      matrix:
        platform:
          - GitHub
          - CurseForge
          - Modrinth
    uses: MinecraftschurliMods/.github/.github/workflows/publish.yml@main
    with:
      platform: ${{ matrix.platform }}
      modid: ${{ needs.build.outputs.modid }}
      version: ${{ needs.build.outputs.version }}
    secrets:
      GH_TOKEN: ${{ matrix.platform == 'GitHub' && secrets.GITHUB_TOKEN || null }}
      CF_API_TOKEN: ${{ matrix.platform == 'CurseForge' && secrets.CF_API_TOKEN || null }}
      MODRINTH_TOKEN: ${{ matrix.platform == 'CurseForge' && secrets.MODRINTH_TOKEN || null }}

#  update-readme:
#    name: Update README
#    runs-on: ubuntu-latest
#    needs:
#      - build
#      - publish
#
#    steps:
#      - name: Checkout
#      - name: Generate Data
#      - name: Render readme
#      - name: Commit readme
#      - name: Bump version number
#      - name: Commit version number
#      - name: Push
#      - name: Create PR

  send-notification:
    name: Send Notification
    runs-on: ubuntu-latest
    needs:
      - build
      - publish

    steps:
      - name: Get Timestamp
        id: timestamp
        uses: nanzm/get-time-action@v2.0
        with:
          format: "YYYY-MM-DDTHH:mm:ssZ"
      - name: Send Notification
        uses: Minecraftschurli/notify-discord-action@main
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          username: "Ars Magica: Legacy"
          avatar_url: https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/blob/version/1.19.x/src/main/resources/logo_small.png?raw=true
          message: "<&1116598471600914492> An update for Ars Magica: Legacy was released!"
          embeds: '[
            {
              "title": "Update Released",
              "timestamp": "${{ steps.timestamp.outputs.time }}",
              "color": "#00ff00",
              "footer": {
                "text": "Ars Magica: Legacy"
              },
              "thumbnail": {
                "url": "https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/blob/version/1.19.x/src/main/resources/logo_small.png?raw=true"
              },
              "author": {
                "name": "${{ github.actor }}",
                "icon_url": "https://avatars.githubusercontent.com/u/${{ github.actor_id }}"
              },
              "fields": [
                { "name": "Version", "value": "`${{ needs.build.outputs.version }}`" },
                { "name": "CurseForge", "value": "[Download](${{ needs.publish.outputs.curseforge-url }})", "inline": true },
                { "name": "Modrinth", "value": "[Download](${{ needs.publish.outputs.modrinth-url }})", "inline": true },
                { "name": "GitHub", "value": "[View](${{ needs.publish.outputs.github-url }})", "inline": true },
                { "name": "Summary", "value": "```${{ needs.build.outputs.summary }}```" }
              ]
            }
          ]'
          allowed_mentions: |
            &1116598471600914492
  
  test-outputs:
    name: Test outputs
    runs-on: ubuntu-latest
    needs:
      - build
      - publish

    steps:
      - name: Test outputs
        run: |
          echo "modrinth-id: ${{ needs.publish.outputs.modrinth-id }}"
          echo "modrinth-version: ${{ needs.publish.outputs.modrinth-version }}"
          echo "modrinth-url: ${{ needs.publish.outputs.modrinth-url }}"
          echo "modrinth-files: ${{ needs.publish.outputs.modrinth-files }}"
          echo "curseforge-id: ${{ needs.publish.outputs.curseforge-id }}"
          echo "curseforge-version: ${{ needs.publish.outputs.curseforge-version }}"
          echo "curseforge-url: ${{ needs.publish.outputs.curseforge-url }}"
          echo "curseforge-files: ${{ needs.publish.outputs.curseforge-files }}"
          echo "github-repo: ${{ needs.publish.outputs.github-repo }}"
          echo "github-tag: ${{ needs.publish.outputs.github-tag }}"
          echo "github-url: ${{ needs.publish.outputs.github-url }}"
          echo "github-files: ${{ needs.publish.outputs.github-files }}"
          echo "modid: ${{ needs.build.outputs.modid }}"
          echo "version: ${{ needs.build.outputs.version }}"
          echo "summary: ${{ needs.build.outputs.summary }}"

#      - name: Post Release
#        uses: Minecraftschurli/post-release-action@main
#        with:
#          webhook-url: ${{ secrets.WEBHOOK_URL }}
#          webhook-name: "Ars Magica: Legacy"
#          webhook-avatar: "https://raw.githubusercontent.com/MinecraftschurliMods/Ars-Magica-Legacy/version/1.19.x/src/main/resources/logo_small.png"
#          webhook-title: "Version {version} of Ars Magica: Legacy released!"
#          webhook-message: ${{ needs.release.outputs.summary }}
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          readme-template: ".github/README_TEMPLATE.md"
#          version: ${{ needs.release.outputs.version }}
#          exclude-links-webhook: "GitHub"
#          published-to: ${{ needs.release.outputs.published-to }}
#          github-link: ${{ needs.release.outputs.github-link }}
#          modrinth-link: ${{ needs.release.outputs.modrinth-link }}
#          curseforge-link: ${{ needs.release.outputs.curseforge-link }}
