name: "Build Release"

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/')
    uses: MinecraftschurliMods/.github/.github/workflows/build.yml@main
    secrets:
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
    with:
      upload-artifacts: true
      artifact-retention: 1
      publish-to-maven: true
      release-type: release
      datagen-folder: src/main/generated/

  publish:
    needs:
      - build
    strategy:
      fail-fast: true
      matrix:
        platform:
          - GitHub
          - CurseForge
          - Modrinth
    uses: MinecraftschurliMods/.github/.github/workflows/publish.yml@main
    with:
      platform: ${{ matrix.platform }}
      modid: ${{ needs.build.outputs.modid }}
      version: ${{ needs.build.outputs.version }}
    secrets:
      GH_TOKEN: ${{ matrix.platform == 'GitHub' && secrets.GITHUB_TOKEN || null }}
      CF_API_TOKEN: ${{ matrix.platform == 'CurseForge' && secrets.CF_API_TOKEN || null }}
      MODRINTH_TOKEN: ${{ matrix.platform == 'CurseForge' && secrets.MODRINTH_TOKEN || null }}

  notify-discord:
    needs:
      - build
      - publish
    uses: MinecraftschurliMods/.github/.github/workflows/notify_discord.yml@main
    with:
      project_name: "Ars Magica: Legacy"
      version: ${{ needs.build.outputs.version }}
      summary: ${{ needs.build.outputs.summary }}
      curseforge_url: ${{ needs.publish.outputs.curseforge-url }}
      modrinth_url: ${{ needs.publish.outputs.modrinth-url }}
      github_url: ${{ needs.publish.outputs.github-url }}
      logo_url: https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/src/main/resources/logo_small.png
      update_ping: "&1116598471600914492"
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

#  update-readme:
#    name: Update README
#    runs-on: ubuntu-latest
#    needs:
#      - build
#      - publish
#
#    steps:
#      - name: Checkout
#      - name: Generate Data
#      - name: Render readme
#      - name: Commit readme
#      - name: Bump version number
#      - name: Commit version number
#      - name: Push
#      - name: Create PR
