name: 'Close stale issues and PR'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v5
        with:
          stale-issue-message: 'This issue is stale because it has been open 60 days with no activity. Remove the stale label or comment on this issue to dismiss the stale status or this issue will be closed in 7 days.'
          stale-pr-message: 'This PR is stale because it has been open 60 days with no activity. Remove the stale label or comment to dismiss the stale status.'
          close-issue-message: 'This issue was closed because it has been stale for 7 days with no activity.'
          days-before-pr-close: -1
          exempt-all-milestones: true
          exempt-all-assignees: true
          exempt-issue-labels: 'fixed in dev'
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
